import { GovernmentUser, RoleConfig, UserRole } from '@/types/auth';

export const ROLE_CONFIGS: Record<UserRole, RoleConfig> = {
  POLICE: {
    label: 'Police & Law Enforcement',
    fullName: 'Investigation Officer / Police Inspector',
    color: 'text-amber-700',
    bgLight: 'bg-amber-50',
    borderColor: 'border-amber-300',
    defaultDept: 'Delhi Police - Crime Branch',
    defaultClearance: 'LEVEL_3',
    description: 'FIR registration, seizure memos, case diaries & evidentiary chain-of-custody logging.',
    iconName: 'ShieldAlert',
  },
  COURT: {
    label: 'Judiciary & Court Registry',
    fullName: 'Judicial Magistrate / High Court Registrar',
    color: 'text-blue-700',
    bgLight: 'bg-blue-50',
    borderColor: 'border-blue-300',
    defaultDept: 'High Court of Judicature - Registry Division',
    defaultClearance: 'LEVEL_5',
    description: 'Charge sheet scrutiny, judicial orders, witness testimonies, bail orders & sealed dockets.',
    iconName: 'Scale',
  },
  FORENSICS: {
    label: 'Forensic Science Laboratory',
    fullName: 'Forensic Director / Senior Scientific Officer',
    color: 'text-purple-700',
    bgLight: 'bg-purple-50',
    borderColor: 'border-purple-300',
    defaultDept: 'Central Forensic Science Laboratory (CFSL)',
    defaultClearance: 'LEVEL_4',
    description: 'Ballistic records, digital cyber-forensics, DNA profiles & toxicology analysis.',
    iconName: 'Microscope',
  },
  LEGAL: {
    label: 'Prosecution & Legal Counsel',
    fullName: 'Public Prosecutor / State Legal Department',
    color: 'text-emerald-700',
    bgLight: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    defaultDept: 'Directorate of Prosecution - MHA',
    defaultClearance: 'LEVEL_3',
    description: 'Trial preparations, evidentiary bundle audit, inter-agency discovery & legal filings.',
    iconName: 'FileCheck',
  },
  NCRB_ADMIN: {
    label: 'NCRB Nodal Oversight',
    fullName: 'NCRB Nodal Cyber & Security Administrator',
    color: 'text-slate-800',
    bgLight: 'bg-slate-100',
    borderColor: 'border-slate-400',
    defaultDept: 'National Crime Records Bureau (NCRB)',
    defaultClearance: 'LEVEL_5',
    description: 'System-wide compliance audit, national crime data synchronization, cryptographic master key oversight.',
    iconName: 'ShieldCheck',
  },
};

export const DEMO_ACCOUNTS: GovernmentUser[] = [
  {
    id: 'usr-police-01',
    name: 'Insp. Vikramaditya Rathore',
    email: 'v.rathore@delhipolice.gov.in',
    role: 'POLICE',
    badgeNumber: 'POL-DL-4091',
    department: 'Delhi Police - Special Crime Division',
    clearanceLevel: 'LEVEL_3',
    stationOrCourt: 'Connaught Place PS (Case Bureau)',
    isMfaVerified: true,
  },
  {
    id: 'usr-court-02',
    name: 'Hon. Registrar S. Venkataraman',
    email: 's.venkat@delhihighcourt.nic.in',
    role: 'COURT',
    badgeNumber: 'JUD-HC-1108',
    department: 'High Court of Delhi - Criminal Registry',
    clearanceLevel: 'LEVEL_5',
    stationOrCourt: 'Court Room #4 & Judicial E-Filing Cell',
    isMfaVerified: true,
  },
  {
    id: 'usr-forensic-03',
    name: 'Dr. Ananya Sen, Ph.D.',
    email: 'dr.ananya@cfsl.gov.in',
    role: 'FORENSICS',
    badgeNumber: 'FSL-CEN-042',
    department: 'Central Forensic Science Laboratory (CFSL)',
    clearanceLevel: 'LEVEL_4',
    stationOrCourt: 'Cyber Forensics & DNA Division',
    isMfaVerified: true,
  },
  {
    id: 'usr-legal-04',
    name: 'Adv. Meera Chawla',
    email: 'm.chawla@prosecution.gov.in',
    role: 'LEGAL',
    badgeNumber: 'PP-MHA-882',
    department: 'Directorate of Prosecution - MHA',
    clearanceLevel: 'LEVEL_3',
    stationOrCourt: 'Tis Hazari Court Legal Chambers',
    isMfaVerified: true,
  },
];
