'use client';

import React, { useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import {
  FileCheck2,
  Scale,
  BookOpen,
  CheckCircle2,
  AlertCircle,
  Download,
  Copy,
  Check,
  Shield,
  FileText,
  HelpCircle,
  ExternalLink,
  ChevronDown,
  ChevronRight,
  Landmark,
  BadgeAlert,
  Info,
} from 'lucide-react';

export default function LegalComplianceView() {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<'statutes' | 'checklist' | 'templates' | 'caselaw'>('statutes');
  const [copiedTemplate, setCopiedTemplate] = useState<string | null>(null);

  // Interactive Court Admissibility Checklist state
  const [checklist, setChecklist] = useState<{ [key: string]: boolean }>({
    regular_use: true,
    ordinary_course: true,
    operating_properly: true,
    reproduction_original: true,
    hash_verified: true,
    chain_of_custody: true,
  });

  const toggleCheck = (key: string) => {
    setChecklist((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const completedCount = Object.values(checklist).filter(Boolean).length;
  const totalCount = Object.keys(checklist).length;
  const compliancePercentage = Math.round((completedCount / totalCount) * 100);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedTemplate(id);
    setTimeout(() => setCopiedTemplate(null), 2000);
  };

  const sample65BCertificate = `IN THE COURT OF THE LEARNED CHIEF METROPOLITAN MAGISTRATE / SESSIONS JUDGE
NEW DELHI DISTRICT, PATIALA HOUSE COURTS, NEW DELHI

IN THE MATTER OF:
STATE (NCT OF DELHI) THROUGH CYBER CRIME POLICE STATION
VERSUS
ACCUSED PERSONS IN FIR NO: 2026/DEL/0482

CERTIFICATE UNDER SECTION 65B OF THE INDIAN EVIDENCE ACT, 1872
[READ WITH SECTION 63 OF BHARATIYA SAKSHYA ADHINIYAM, 2023]

I, ${user?.name || 'Investigating Officer'}, currently designated as ${user?.role === 'POLICE' ? 'Inspector of Police' : 'Authorized Officer'} at ${user?.stationOrCourt || 'Cyber Crime Division, Delhi Police'}, holding Police Badge / Identification No: ${user?.badgeNumber || 'POL-DL-4091'}, do hereby solemnly affirm, certify and declare under oath as follows:

1. That I am the authorized officer having lawful control and custody over the electronic processing unit and computer system registered under GovTech Node DEL-NCRB-01 during the period when the digital record was produced.

2. That the digital output / evidence docket bearing Hash ID (SHA-256):
   [9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08]
   was generated by the said computer system during the period over which the computer was used regularly to store and process electronic records for judicial investigation purposes.

3. That throughout the said period, information of the kind contained in the electronic record was regularly fed into the computer in the ordinary course of the said official investigative activities.

4. That throughout the material part of the said period, the computer system was operating properly and at no point in time did any malfunction or operational defect affect the production or accuracy of the said electronic record or the cryptographic bitstream contents thereof.

5. That the printout / reproduction annexed herewith is an exact, uncorrupted, and true bit-level duplicate reproduction of the original electronic record preserved under strict cryptographic hash verification and unbroken Chain of Custody.

DEPONENT:
${user?.name || 'Authorized Officer'}
Badge No: ${user?.badgeNumber || 'POL-DL-4091'}
Jurisdiction: ${user?.stationOrCourt || 'Delhi Police'}
Date of Certification: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
GovTech Node ID: DEL-NCRB-NODE-01`;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header Banner */}
      <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4 card-hover">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-blue-700 bg-blue-50 border border-blue-200 px-2.5 py-0.5 rounded-full flex items-center gap-1.5 font-mono">
              <Scale className="w-3.5 h-3.5 text-blue-600" />
              <span>Statutory Compliance &amp; Legal Framework</span>
            </span>
            <span className="text-xs text-slate-400">•</span>
            <span className="text-xs text-slate-500 font-mono">IEA Sec 65B &amp; BSA 2023 Sec 63</span>
          </div>
          <h2 className="text-2xl font-bold text-slate-900 tracking-tight">
            Indian Evidence Act &amp; Judicial Admissibility Knowledgebase
          </h2>
          <p className="text-xs text-slate-600 max-w-2xl">
            Authoritative guidelines, Supreme Court constitutional precedents, mandatory 4-condition compliance
            checklists, and automated certificate generation for electronic court evidence.
          </p>
        </div>

        {/* Admissibility Scorecard Pill */}
        <div className="bg-slate-50 border border-slate-200 rounded-xl p-3.5 text-right shrink-0">
          <span className="text-[10px] uppercase font-bold text-slate-500 block">Current Admissibility Score</span>
          <div className="flex items-center justify-end gap-2 mt-0.5">
            <span className="text-2xl font-black text-slate-900 font-mono">{compliancePercentage}%</span>
            <span
              className={`text-[10px] font-bold px-2 py-0.5 rounded font-mono ${
                compliancePercentage === 100
                  ? 'bg-emerald-100 text-emerald-800'
                  : 'bg-amber-100 text-amber-800'
              }`}
            >
              {compliancePercentage === 100 ? 'COURT ADMISSIBLE' : 'PENDING CHECKS'}
            </span>
          </div>
          <span className="text-[10px] text-slate-400 block mt-0.5">
            {completedCount} of {totalCount} statutory criteria fulfilled
          </span>
        </div>
      </div>

      {/* Navigation Sub-Tabs */}
      <div className="flex border-b border-slate-200 bg-white rounded-xl p-1 gap-1 shadow-xs">
        <button
          type="button"
          onClick={() => setActiveTab('statutes')}
          className={`flex-1 py-2 px-3 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${
            activeTab === 'statutes'
              ? 'bg-slate-900 text-white shadow-xs'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
          }`}
        >
          <BookOpen className="w-3.5 h-3.5" />
          <span>Statutory Framework</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('checklist')}
          className={`flex-1 py-2 px-3 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${
            activeTab === 'checklist'
              ? 'bg-slate-900 text-white shadow-xs'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
          }`}
        >
          <FileCheck2 className="w-3.5 h-3.5" />
          <span>Section 65B 4-Condition Checklist</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('templates')}
          className={`flex-1 py-2 px-3 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${
            activeTab === 'templates'
              ? 'bg-slate-900 text-white shadow-xs'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
          }`}
        >
          <FileText className="w-3.5 h-3.5" />
          <span>Statutory Affidavit Templates</span>
        </button>

        <button
          type="button"
          onClick={() => setActiveTab('caselaw')}
          className={`flex-1 py-2 px-3 text-xs font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${
            activeTab === 'caselaw'
              ? 'bg-slate-900 text-white shadow-xs'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
          }`}
        >
          <Landmark className="w-3.5 h-3.5" />
          <span>Supreme Court Precedents</span>
        </button>
      </div>

      {/* Tab 1: Statutory Framework */}
      {activeTab === 'statutes' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                Primary Statute
              </span>
              <span className="text-xs font-semibold text-slate-500">Sec 65B(1) to 65B(4)</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Section 65B: Indian Evidence Act, 1872
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Provides that any electronic record printed on paper, stored, recorded, or copied in optical or magnetic
              media shall be deemed to be a document and shall be admissible in any judicial proceeding without further
              proof of the original, subject to four mandatory operational conditions.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 font-mono text-slate-700">
              <p>• Mandatory condition (a): Regular lawful use of the computer.</p>
              <p>• Mandatory condition (b): Regular feeding in ordinary course.</p>
              <p>• Mandatory condition (c): Flawless operational state.</p>
              <p>• Mandatory condition (d): Unaltered bit-level reproduction.</p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-purple-700 bg-purple-50 px-2 py-0.5 rounded border border-purple-200">
                New Criminal Law 2024
              </span>
              <span className="text-xs font-semibold text-slate-500">Sec 63</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Section 63: Bharatiya Sakshya Adhiniyam, 2023 (BSA)
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Modernizes electronic evidence rules across India. Recognizes server logs, cloud storage, encrypted
              communication channels, and electronic signatures as primary evidence when properly authenticated with
              cryptographic certificates and hash registers under the Schedule to Section 63.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 font-mono text-slate-700">
              <p>• Schedule Part A: System Custody &amp; Operational Log declaration.</p>
              <p>• Schedule Part B: Expert Cryptographic Hash Verification.</p>
              <p>• Electronic records stored across distributed nodes validated.</p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-amber-700 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">
                Cyber Offences
              </span>
              <span className="text-xs font-semibold text-slate-500">Sec 65, 66, 79A</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Information Technology Act, 2000 (Amended)
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Establishes statutory definitions for digital signatures, electronic governance, and tamper liability.
              Section 79A empowers the Central Government to notify Central Forensic Science Laboratories (CFSL) as
              official Examiners of Electronic Evidence with binding evidentiary authority.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 font-mono text-slate-700">
              <p>• Sec 65: Tampering with computer source documents (Cognizable).</p>
              <p>• Sec 66: Computer related offences &amp; unauthorized access.</p>
              <p>• Sec 79A: Central Government accredited Examiner of Evidence.</p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                International Standard
              </span>
              <span className="text-xs font-semibold text-slate-500">ISO/IEC 27037:2012</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Digital Evidence Handling Standard Operating Procedure
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              International gold standard for identification, collection, acquisition, and preservation of digital
              evidence. Secure-Doc enforces ISO 27037 compliance via hardware write-blocker emulation, dual-algorithm
              hashing (SHA-256 + SHA-512), and unbroken cryptographic custody logs.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 font-mono text-slate-700">
              <p>• Principle 1: No action taken should alter data on storage media.</p>
              <p>• Principle 2: Persons handling digital evidence must be competent.</p>
              <p>• Principle 3: Complete audit trail of all processes must be preserved.</p>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Section 65B Checklist */}
      {activeTab === 'checklist' && (
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs card-hover space-y-5">
          <div className="pb-3 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Statutory 4-Condition Admissibility Audit Checklist
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Every digital evidence file must satisfy the four mandatory prongs of Section 65B(2) to be admissible in
                an Indian Court of Law without producing the physical server.
              </p>
            </div>
            <span className="text-xs font-mono font-bold text-slate-700 bg-slate-100 px-3 py-1 rounded-md">
              Patiala House / High Court Standard
            </span>
          </div>

          <div className="space-y-3">
            {[
              {
                id: 'regular_use',
                condition: 'Condition 1: Section 65B(2)(a) - Regular Lawful Custody & Operation',
                desc: 'The computer output containing information was produced by the computer during the period over which the computer was used regularly to store or process information for the purposes of any activities regularly carried on by the person having lawful control.',
                badge: 'MANDATORY',
              },
              {
                id: 'ordinary_course',
                condition: 'Condition 2: Section 65B(2)(b) - Fed in Ordinary Course of Duty',
                desc: 'During the said period, information of the kind contained in the electronic record, or of the kind from which the information so contained is derived, was regularly fed into the computer in the ordinary course of the said activities.',
                badge: 'MANDATORY',
              },
              {
                id: 'operating_properly',
                condition: 'Condition 3: Section 65B(2)(c) - Uncompromised Operational Accuracy',
                desc: 'Throughout the material part of the said period, the computer was operating properly or, if not, that in respect of any period in which it was not operating properly, the production of the electronic record was not affected.',
                badge: 'MANDATORY',
              },
              {
                id: 'reproduction_original',
                condition: 'Condition 4: Section 65B(2)(d) - Faithful Reproduction of Original',
                desc: 'The information contained in the electronic record reproduces or is derived from such information fed into the computer in the ordinary course of the said activities, without unauthorized tampering or bit modification.',
                badge: 'MANDATORY',
              },
              {
                id: 'hash_verified',
                condition: 'Cryptographic Integrity: NIST SHA-256 Digest Match',
                desc: 'The cryptographic SHA-256 hash of the presented digital document matches bit-for-bit with the initial seizure memo panchnama hash recorded on the immutable ledger.',
                badge: 'FORENSIC',
              },
              {
                id: 'chain_of_custody',
                condition: 'Unbroken Chain of Custody (ISO 27037)',
                desc: 'All transfers between Investigating Officer (IO), Central Forensic Science Lab (CFSL), Directorate of Prosecution, and Judicial Court are signed with verifiable officer PKI certificates.',
                badge: 'PROCEDURAL',
              },
            ].map((item) => {
              const isChecked = checklist[item.id];
              return (
                <div
                  key={item.id}
                  onClick={() => toggleCheck(item.id)}
                  className={`p-4 rounded-xl border transition-all cursor-pointer flex items-start gap-3.5 ${
                    isChecked
                      ? 'bg-slate-50 border-slate-300 hover:border-slate-400'
                      : 'bg-red-50/50 border-red-200 hover:border-red-300'
                  }`}
                >
                  <div className="mt-0.5 shrink-0">
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => {}}
                      className="w-4 h-4 text-blue-600 rounded border-slate-300 focus:ring-blue-500 cursor-pointer"
                    />
                  </div>

                  <div className="flex-1 space-y-1">
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-xs font-bold text-slate-900">{item.condition}</p>
                      <span className="text-[9px] font-mono font-bold px-1.5 py-0.5 rounded bg-slate-200 text-slate-700">
                        {item.badge}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600 leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Tab 3: Affidavit Templates */}
      {activeTab === 'templates' && (
        <div className="space-y-4">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-200">
              <div>
                <h3 className="text-sm font-bold text-slate-900">
                  Official Section 65B Evidentiary Certificate Template (Patiala House Courts Format)
                </h3>
                <p className="text-xs text-slate-500 mt-0.5">
                  Pre-populated with active officer session credentials, GovTech Enclave node ID, and statutory sworn clauses.
                </p>
              </div>

              <button
                type="button"
                onClick={() => copyToClipboard(sample65BCertificate, 'cert65b')}
                className="px-3.5 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold hover:bg-slate-800 transition flex items-center gap-2 shadow-xs shrink-0"
              >
                {copiedTemplate === 'cert65b' ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Copied to Clipboard</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-slate-400" />
                    <span>Copy Sworn Certificate</span>
                  </>
                )}
              </button>
            </div>

            <pre className="p-4 bg-slate-900 text-slate-200 rounded-lg text-xs font-mono leading-relaxed overflow-x-auto whitespace-pre-wrap select-all max-h-96">
              {sample65BCertificate}
            </pre>
          </div>
        </div>
      )}

      {/* Tab 4: Supreme Court Precedents */}
      {activeTab === 'caselaw' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                Landmark 3-Judge Bench
              </span>
              <span className="text-xs font-mono text-slate-500">(2020) 7 SCC 1</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Arjun Panditrao Khotkar v. Kailash Kushanrao Gorantyal
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              The Supreme Court authoritatively ruled that Section 65B certificate is an absolute condition precedent to
              the admissibility of secondary electronic records. Production of certificate at the time of filing the
              charge sheet is mandatory, overruling Shafhi Mohammad.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 text-slate-700">
              <p className="font-semibold text-slate-900">Core Judicial Holding:</p>
              <p className="text-slate-600">
                &ldquo;Where original device is not produced in court, certificate under Section 65B(4) is mandatory.
                Electronic records without certificate are inadmissible in law.&rdquo;
              </p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs card-hover space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-100">
              <span className="text-xs font-mono font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                Constitution Principle
              </span>
              <span className="text-xs font-mono text-slate-500">(2014) 10 SCC 473</span>
            </div>
            <h3 className="text-base font-bold text-slate-900">
              Anvar P.V. v. P.K. Basheer &amp; Ors.
            </h3>
            <p className="text-xs text-slate-600 leading-relaxed">
              Established that Section 65B is a complete code in itself relating to the admissibility of electronic
              records. Special provisions under Section 65B prevail over general provisions regarding secondary evidence
              under Section 63 and 65.
            </p>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg text-xs space-y-1 text-slate-700">
              <p className="font-semibold text-slate-900">Core Judicial Holding:</p>
              <p className="text-slate-600">
                &ldquo;General rules of secondary evidence under Sections 63 and 65 yield to the special regime enacted
                in Section 65B.&rdquo;
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
